---
- name: Deploy
  hosts: all
  become: yes

  tasks:
  - name: Update cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install Docker
    apt:
      name: docker
      state: latest

  - name: Install docker-compose
    apt:
      name: docker-compose
      state: latest

  - name: Transfer the docker-compose file
    copy: src=docker-compose.yml dest=/wp mode=0777

  - name: Docker compose UP
    shell: docker-compose -f /wp/docker-compose.yml up -d
